# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:root@tcp(127.0.0.1:3306)/gfast"
        tables:          "Attachments,CheatInfo,Containers,ExerciseChallenges,ExerciseDependencies,ExerciseInstances,Files,FlagContexts,GameChallenges,GameEvents,GameInstances,GameNotices,Games,Logs,Participations,Posts,Submissions,Teams,TeamUserInfo,UserParticipations"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/kube"